// ESLint flat config (ESLint v9)
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import astro from "eslint-plugin-astro";
import globals from "globals";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import unusedImports from "eslint-plugin-unused-imports";
import eslintPluginImport from "eslint-plugin-import";

// Fallback for Astro flat config if unavailable
const astroFlat = astro.configs?.["flat/recommended"]; // prefer flat config if plugin supports it

export default [
  // Ignore generated/third-party
  { ignores: ["dist/**", ".astro/**", "node_modules/**"] },

  // JavaScript base
  {
    ...js.configs.recommended,
    files: ["**/*.{js,jsx}"],
    languageOptions: {
      sourceType: "module",
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: { "simple-import-sort": simpleImportSort, import: eslintPluginImport, "unused-imports": unusedImports },
    rules: {
      "simple-import-sort/imports": "error",
      "simple-import-sort/exports": "error",
      "import/first": "error",
      "import/newline-after-import": "error",
      "unused-imports/no-unused-imports": "error",
      "unused-imports/no-unused-vars": ["warn", { args: "after-used", argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
    },
  },

  // TypeScript (non type-aware + type-aware layer)
  ...tseslint.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      parserOptions: {
        project: ["./tsconfig.json"],
        tsconfigRootDir: new URL(".", import.meta.url).pathname,
      },
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: { "simple-import-sort": simpleImportSort, import: eslintPluginImport, "unused-imports": unusedImports },
    rules: {
      "@typescript-eslint/consistent-type-definitions": ["warn", "interface"],
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-floating-promises": "error",
      "simple-import-sort/imports": "error",
      "simple-import-sort/exports": "error",
      "import/first": "error",
      "import/newline-after-import": "error",
      "unused-imports/no-unused-imports": "error",
      "unused-imports/no-unused-vars": ["warn", { args: "after-used", argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "@typescript-eslint/no-unused-vars": "off", // unused-importsに委譲
    },
  },

  // Astro (.astro) files
  ...(astroFlat
    ? astroFlat
    : [
        {
          files: ["**/*.astro"],
          languageOptions: {
            parser: astro.parser,
            parserOptions: {
              // Use TS parser inside <script> blocks
              parser: tseslint.parser,
            },
            globals: { ...globals.browser },
          },
          plugins: { astro },
          rules: {
            ...astro.configs.recommended.rules,
            "@typescript-eslint/no-explicit-any": "off",
            "@typescript-eslint/no-floating-promises": "off",
          },
        },
      ]),
  // Ensure our Astro-specific overrides apply even if using plugin's flat config
  {
    files: ["**/*.astro"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-floating-promises": "off",
    },
  },
  // Disable type-aware rules for Astro virtual TS files generated by the processor
  {
    files: ["**/*.astro/*", "**/*.astro/*.ts"],
    rules: {
      "@typescript-eslint/no-floating-promises": "off",
    },
  },
];
